# supabase/config.toml

project_id = "fsgabmgomgblwihchaso"
name = "al-finance"

[functions.create-investor]
secrets = ["SUPABASE_URL", "SUPABASE_SERVICE_ROLE_KEY"]

[functions.create-subordinate]
secrets = ["SUPABASE_URL", "SUPABASE_SERVICE_ROLE_KEY"]

[functions.register-office-manager]
secrets = ["SUPABASE_URL", "SUPABASE_SERVICE_ROLE_KEY"]
